### PR TITLE
Update CI, TagBot and documentation workflows

### PR DESCRIPTION
**Pull request by JSOBot**

### CODE REVIEW

**Comment by dpo** [comment]
Needs docs.

**Comment by abelsiqueira** [comment]
@geoffroyleconte, there should be a way to adapt https://github.com/JuliaSmoothOptimizers/DCISolver.jl/blob/master/docs/src/reference.md to the each package. It automatically load the docstrings, so there's no error.

**Comment by dpo** [comment]
I think you mean to ping @MonssafToukal

**Comment by abelsiqueira** [comment]
That's right, sorry @geoffroyleconte.

**Pull request merged**
